.github/workflows/managedshell.yml, src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs
Send more events for version 3 icons (cairoshell/cairoshell#517)
Remove version hack superseded by ExplorerTrayService
Fix logging for NIM_DELETE
Fix icon hide/un-hide after icon added (fixes Spotify)
Fix bad icon version updates being allowed
=> Improve tray compatibility

src/ManagedShell.Common/Common/ThreadSafeObservableCollection.cs, src/ManagedShell.Common/Enums/StartupEntryScope.cs, src/ManagedShell.Common/Enums/StartupEntryType.cs, src/ManagedShell.Common/Helpers/SearchHelper.cs, src/ManagedShell.Common/Helpers/ShellHelper.cs, src/ManagedShell.Common/ManagedShell.Common.csproj, src/ManagedShell.Common/Structs/StartupEntry.cs, src/ManagedShell.Common/Structs/StartupLocation.cs, src/ManagedShell.Common/SupportingClasses/NativeWindowEx.cs, src/ManagedShell.Common/SupportingClasses/SearchObjectState.cs, src/ManagedShell.Common/SupportingClasses/SearchResult.cs, src/ManagedShell.Common/SupportingClasses/ShellWindow.cs, src/ManagedShell.Common/SupportingClasses/StartupRunner.cs, src/ManagedShell.Interop/ManagedShell.Interop.csproj, src/ManagedShell.Interop/WindowsServices.cs, src/ManagedShell.WindowsTasks/TasksService.cs, src/ManagedShell/ManagedShell.csproj
Modified StartupRunner to use standard types
Modified SearchHelper to use custom search query which has better result ordering
Modified SearchHelper to perform search in background task and removed bad old threading code
=> Add SearchHelper, ShellWindow, StartupRunner

src/ManagedShell.ShellFolders/ShellFolder.cs, src/ManagedShell.ShellFolders/ShellItem.cs, src/ManagedShell.UWPInterop/ManagedShell.UWPInterop.csproj, src/ManagedShell.UWPInterop/StoreApp.cs, src/ManagedShell.UWPInterop/StoreAppHelper.cs, src/ManagedShell.UWPInterop/StoreAppList.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs
- Reworked how store apps are retrieved to make it more straightforward for the shell
- Adds store app icon fallback to ShellFolders
- Be less restrictive of taskbar store app visibility
- Adds option to create ShellFolder without change watcher
- Adds option to disable async ShellFolders icon fetch
=> Refactored store app logic

src/ManagedShell.Common/Helpers/ShellHelper.cs, src/ManagedShell.Interop/NativeMethods.Kernel32.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs
- Moved AUMID logic out of `ApplicationWindow` into `ShellHelper.GetAppUserModelIdPropertyForHandle`
- Added implicit AUMID fetch for Windows 8+ with `ShellHelper.GetAppUserModelIdForHandle`. Not using with `ApplicationWindow` because it unfortunately doesn't offer any relevant benefits.
- Label tasks logging
- Improve UWP window hiding logic
=> Misc tasks changes

src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs
Accessible via two new properties to `ApplicationWindow`:
- `OverlayIcon`
- `OverlayIconDescription`
=> Adds support for ITaskbarList3::SetOverlayIcon

src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs
- Fix ITaskbarList on existing windows when shell starts
- Fix ITaskbarList on Explorer taskbar after shell exits
- Fix flashing task behavior to be more correct
=> Tasklist fixes

src/ManagedShell.WindowsTasks/ApplicationWindow.cs
Fixes crash when running https://api.flybywiresim.com/installer
=> Avoid accessing invalid memory

src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs
- Added Orientation convenience property to AppBarWindow
- Implemented INotifyPropertyChanged for AppBarWindow edge/orientation properties
- Fixed some immersive shell windows showing on taskbar in Windows 8
=> Misc refactor

src/ManagedShell.Common/Helpers/SoundHelper.cs, src/ManagedShell.WindowsTray/NotificationBalloon.cs
Also made public NotificationBalloon methods safer
=> Add SoundHelper

src/ManagedShell.AppBar/AppBarManager.cs
=> Fix backwards appbar calculation

src/ManagedShell.Common/Helpers/ShellHelper.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTray/NotificationArea.cs
Also removes obsolete string replace from and renamed GetPathForHandle
=> Add WinFileDescription to ApplicationWindow

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/ExplorerHelper.cs
Oops. This should fix cairoshell/cairoshell#658.
=> Fix NRE when notification area is not enabled

src/ManagedShell.Common/Helpers/ShellHelper.cs
200ms is too short especially when Cairo is exiting and Explorer is doing things. I was running into this timeout most of the time on my VMs.
Also changed the timeout option to not immediately abort if Explorer is hung.
=> Increase desktop icon message timeout

src/ManagedShell.WindowsTray/NotifyIcon.cs
This should fix cairoshell/cairoshell#668.
=> Fix notify icon pinning issues

src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs
Also make some constants public
=> Fix regressions from #55

src/ManagedShell.AppBar/AppBarWindow.cs
When we move a window to a monitor that has a different DPI than the main display DPI ("system DPI"), Windows sends a WM_DPICHANGED message to the window telling it as such. However, when we move the window to that display, we have already given it the correct coordinates, so we do not need to handle the WM_DPICHANGED message.
Before, when we did handle WM_DPICHANGED in this scenario, we moved the window to the wrong place, which would send another WM_DPICHANGED message, causing it to move back to the correct place, and so on in an infinite loop until hitting the Windows message quota.
The fix for this is to suppress handling WM_DPICHANGED when the window is being positioned initially.
Also fixed another DPI-related issue when Application.Current.MainWindow was not on the primary display.
=> Fix infinite loop in some mixed DPI setups

src/ManagedShell.Common/Common/ThreadSafeObservableCollection.cs
This looks like it could be the cause of dremin/RetroBar#560.
=> Fix thread safety issue in bounds checking

.github/dependabot.yml
Inspired by cairoshell/cairoshell#765 to keep these up to date (the action versions are quite outdated right now)
=> Add dependabot config for actions

src/ManagedShell.WindowsTray/NotifyIcon.cs
This should address dremin/RetroBar#703
=> Support middle clicking notify icons

src/ManagedShell.AppBar/AppBarWindow.cs
Some operations should not respect the show delay, such as disabling auto-hide, or issuing a peek command.
Also adjusted the default peek time now that it doesn't respect the delays.
=> Fix behavior with auto-hide show delay > 0

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.Common/Helpers/DpiHelper.cs, src/ManagedShell.ShellFolders/ShellItem.cs, src/ManagedShell.WindowsTray/TrayService.cs
Fixes some issues with DPI scaling:
- cairoshell/cairoshell#795
- dremin/RetroBar#735
=> Round window metrics when converting

src/ManagedShell.AppBar/AppBarWindow.cs
After #77 this is no longer needed and can cause race problems.
=> Remove another no-longer-needed hack

src/ManagedShell.Common/Logging/ShellLogger.cs
If ShellLogger received log events before an observer was attached, now we retain them and the shell can tell us to re-emit them when it attaches its observer(s).
=> Allow re-emitting logs from before the first observer was attached

src/ManagedShell.ShellFolders/Enums/CommonContextMenuVerb.cs
These are being moved out of Cairo by cairoshell/cairoshell#816.
=> Add enum (well, class) with common shell verbs

src/ManagedShell.WindowsTasks/TasksService.cs
Allows the shell to re-initialize it if desired.
=> Fully dispose TasksService

src/ManagedShell.Common/Helpers/WindowHelper.cs
=> Fix peek parameter
