src/ManagedShell.Common/Helpers/IconHelper.cs, src/ManagedShell.Common/Helpers/IconImageConverter.cs, src/ManagedShell.Interop/NativeMethods.Shell32.cs, src/ManagedShell.ShellFolders/Interop.cs, src/ManagedShell.ShellFolders/ShellFolder.cs, src/ManagedShell.ShellFolders/ShellItem.cs, src/ManagedShell.ShellFolders/ShellItemContextMenu.cs, src/ManagedShell.ShellFolders/ShellMenuCommandBuilder.cs
- Requests to load the desktop folder now get it using SHGetDesktopFolder, which combines user and common desktop, and fixes loading that folder on Windows 7
- Added icon fallback to SHGetFileInfo for Windows Server
- Fall back to root shell item if unable to get parent of provided item
- Fixed use after free caused by desktop changes
- Added ability to define a custom default item in context menus
- Added ability to optionally override the open action for navigable folders
=> Shell folders compatibility improvements

src/ManagedShell.Interop/KnownFolders.cs, src/ManagedShell.Interop/NativeMethods.Shell32.cs, src/ManagedShell.ShellFolders/ChangeWatcher.cs, src/ManagedShell.ShellFolders/Enums/ShellFolderPath.cs, src/ManagedShell.ShellFolders/ShellContextMenu.cs, src/ManagedShell.ShellFolders/ShellFolder.cs, src/ManagedShell.ShellFolders/ShellItemContextMenu.cs
- Allow `ChangeWatcher` to watch multiple folders, use for both desktop folders
- Simplify and improve context menu handlers
- Add methods to get known folders that `Environment.SpecialFolder` doesn't provide
=> More shell folders fixes

.github/workflows/managedshell.yml, src/ManagedShell.Common/Helpers/SearchHelper.cs, src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs, src/ManagedShell.WindowsTray/SafeNotifyIconData.cs
- Fix `SearchHelper` specifying invalid column names in Windows 7 and 8
- Handle potential 32-bit overflow in the tray
- Fix notify icon focus issue and remove hack (cairoshell/cairoshell#498)
- Split notify icon mousedown and mouseup events
=> Misc fixes

src/ManagedShell.Common/Helpers/EnvironmentHelper.cs, src/ManagedShell.Common/Helpers/WindowHelper.cs, src/ManagedShell.Interop/NativeMethods.UxTheme.cs, src/ManagedShell.ShellFolders/ShellFolderContextMenu.cs, src/ManagedShell.ShellFolders/ShellItemContextMenu.cs
- Shell app needs to call `WindowHelper.SetDarkModePreference` before context menus can become dark
- Also adds ability to disable rename option from appearing in item context menus
=> Add context menu dark mode support for 1903-20H2

src/ManagedShell.Common/Helpers/IconHelper.cs
Originally thought these weren't supported, but it actually works.
=> Allow jumbo icons outside ShellFolders

src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs
Dramatically reduces the number of times GetCategory is called. The consuming shell only has access to visible windows, so there's no reason to perform the work on non-visible windows (which is the vast majority).
=> Get task category only for visible tasks

src/ManagedShell.Common/Helpers/EnvironmentHelper.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs
Also fixes a UWP task visibility regression in newer Windows builds caused by a recent change.
=> Allow dark mode support in 21H1

src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs
Always use SC_RESTORE or SC_MINIMIZE as that is what Explorer does. This takes care of cairoshell/cairoshell#564.
Also added minor optimization to TasksService.
=> Improve minimize/restore behavior

src/ManagedShell.Common/Helpers/GroupPolicyHelper.cs, src/ManagedShell.WindowsTray/NotificationArea.cs
Adds GPO support to hide the following icons:
- Action Center (Windows 7/8)
- Battery
- Meet Now (Windows 10)
- Network
Volume was already supported.
Reference: cairoshell/cairoshell#588
=> Support GPO for hiding system notification area icons

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/ExplorerHelper.cs, src/ManagedShell.WindowsTray/TrayService.cs
As opposed to the current strategy of always suspending our tray for each AppBar message. It seems forwarding works fine from our tray to Explorer for all AppBar messages sent by our own windows, except ABM_[GET/SET]POS, which use shared memory.
This results in better tray reliability as fewer messages are missed.
=> Forward more AppBar messages

src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.AppBar/ExplorerHelper.cs, src/ManagedShell.Common/Helpers/WindowHelper.cs, src/ManagedShell.WindowsTray/TrayService.cs
1. Merges `ExplorerHelper.FindTaskbarHwnd` and `TrayService.FindWindowsTray` to `WindowHelper.FindWindowsTray`
2. Creates a monitor that will bring our Shell_TrayWnd to the top if the Explorer Shell_TrayWnd becomes topmost. This is more important now that the suspend/resume, which forced us back to the top, is used significantly less after #26.
3. Creates a monitor that will hide the Explorer taskbar if it is shown while `HideExplorerTaskbar == true`. This fixes the Explorer taskbar showing up in circumstances that we cannot predict. Removed usages and ability to force-hide it elsewhere since that is no longer needed.
=> More reliably keep notification area running & taskbar hidden

src/ManagedShell.Common/Enums/MONITOR_APP_VISIBILITY.cs, src/ManagedShell.Common/Helpers/AppVisibilityHelper.cs, src/ManagedShell.Common/Interfaces/IAppVisibility.cs, src/ManagedShell.Common/Interfaces/IAppVisibilityEvents.cs, src/ManagedShell.Common/SupportingClasses/AppVisibility.cs, src/ManagedShell.Common/SupportingClasses/AppVisibilityEventArgs.cs, src/ManagedShell.Common/SupportingClasses/AppVisibilityEvents.cs, src/ManagedShell.Common/SupportingClasses/LauncherVisibilityEventArgs.cs, src/ManagedShell.WindowsTray/TrayService.cs
Adds IAppVisibility functionality via AppVisibilityHelper. Query functionality works on Windows 8 or later, subscribing to events requires Windows 10 or later because of an access violation in system DLLs on Windows 8.
The primary use case of IAppVisibility is to know when the start menu is open.
=> IAppVisibility

src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/TrayService.cs
This fixes Volume2 positioning (dremin/RetroBar#81). ManagedShell originally positioned the Shell_TrayWnd at the same place as the Cairo menu bar due to legacy. Now, it moves to the position specified by the shell.
=> Set tray window position from TrayHostSizeData

src/ManagedShell.Interop/NativeMethods.Shell32.cs, src/ManagedShell.WindowsTray/BalloonVisibility.cs, src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/NotificationBalloon.cs, src/ManagedShell.WindowsTray/NotificationBalloonEventArgs.cs, src/ManagedShell.WindowsTray/NotificationBalloonInfo.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs, src/ManagedShell.WindowsTray/SafeNotifyIconData.cs
- `NotificationBalloon` class represents the received notification
- 2 new events that the consuming shell can subscribe to:
- `NotificationArea.NotificationBalloonShown` => Runs for every received notification
- `NotifyIcon.NotificationBalloonShown` => Runs for the `NotifyIcon` associated to the notification if the above event was not handled
- If no balloon event is handled, the notification is added to the `NotifyIcon.MissedNotifications` collection
- Methods for sending `NIN_*` messages that applications expect after providing a notification
- Misc refactors
=> Notification balloon support

src/ManagedShell.Common/Helpers/SoundHelper.cs, src/ManagedShell.WindowsTray/NotificationBalloon.cs
Makes minor fixes in #36 (uses the correct audio session for system notifications, used to use the application's own), and #35 (uses the correct icons to display in the tooltip balloon, used to fail to display the error icon showing the info icon instead).
=> Notification balloon fixes

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/AppBarWindow.cs
- Fix calculation of existing AppBar sizes on the left or top edge of non-primary displays
- Fix AfterAppBarPos timer starting before the tick action is defined
=> Misc AppBar fixes

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/ExplorerHelper.cs, src/ManagedShell.Interop/NativeMethods.Shell32.cs, src/ManagedShell.WindowsTray/Delegates.cs, src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/TrayService.cs
Fixes apps incorrectly thinking the taskbar is auto-hide.
Some apps, notably Firefox and Chromium-based apps, add a few pixels to the edge of their window if the taskbar is set to auto-hide (presumably to prevent the 2 pixels of remaining taskbar from covering the browser). Currently, when a ManagedShell app is running, the request gets forwarded to Explorer, which has an auto-hidden taskbar, so apps always think that auto-hide is enabled.
This PR causes ManagedShell to handle ABM_GETSTATE and ABM_GETAUTOHIDEBAR messages, which is what apps use to tell if the taskbar is auto-hidden.
I added plumbing for AppBarManager to provide information regarding AppBarWindows that are autohidden, however AppBarWindow doesn't currently have a concept of auto-hide, so effectively this always returns the …
=> Handle AppBar state requests

src/ManagedShell.Common/Enums/ShellFolderPath.cs, src/ManagedShell.Common/Helpers/ShellHelper.cs, src/ManagedShell.UWPInterop/StoreApp.cs, src/ManagedShell.UWPInterop/StoreAppHelper.cs
Also change UWP apps to run directly from `shell:appsfolder`.
These changes will allow shells to run eligible UWP apps as admin (cairoshell/cairoshell#605)
=> Consolidate StartProcess, add EntryPoint to StoreApp

src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.Common/Helpers/ShellHelper.cs, src/ManagedShell.ShellFolders/ShellContextMenu.cs, src/ManagedShell.ShellFolders/ShellFolderContextMenu.cs, src/ManagedShell.ShellFolders/ShellItemContextMenu.cs
Sets the working directory for commands executed via `IContextMenu` from filesystem folders, and adds the ability to set it from `ShellHelper.StartProcess`.
This is needed to take care of cairoshell/cairoshell#640.
Also includes a drive-by fix to prevent an exception when AppBar gives us negative dimensions.
=> Set working directory

src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs
- Add `AllIcons` collection which combines pinned and unpinned icons ignoring pinned order
- Use public setter for `NotifyIcon.IsPinned`
=> Make it easier to deal with pinned notify icons

src/ManagedShell.AppBar/AppBarManager.cs
At the end of ABSetPos, we check if the AppBar's resulting height is the desired height. This was correct when we only supported horizontal AppBars, but causes an infinite loop for vertical AppBars when another horizontal AppBar is present (dremin/retrobar#186).
This changes the sanity check to check the resulting width for vertical AppBars rather than height.
=> Fix AppBar sanity checking to properly handle vertical AppBars

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/ExplorerHelper.cs, src/ManagedShell.Interop/NativeMethods.Shell32.cs, src/ManagedShell.Interop/NativeMethods.ShlwApi.cs, src/ManagedShell.WindowsTray/Delegates.cs, src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/TrayService.cs
- Added handling for ABM_QUERYPOS and ABM_SETPOS. These messages use shared memory to allow the shell to adjust the AppBarData and be returned to the caller. Previously we just forwarded these on to Explorer as-is, but it couldn't use the shared memory marked with our PID. Now, we open up the shared memory sent to us, then create new shared memory to send on to Explorer, which it is able to use.
- Removed suspend/resume tray functionality hack, since it is no longer needed due to properly working forwarding.
- Refactored AppBarMessage handling to reside fully within AppBarManager
- Reverted setting Explorer taskbar state to not be async due to inconsistent behavior
- Fixed another 'hard-coded' tray size reference
- Improved some code comments
This set of fixes addresses Windows 7 …
=> Fix AppBar shared memory handling, remove workarounds

src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs
Helps with buggy programs like FastStone Capture (dremin/RetroBar#261), which use a new UID each launch, so we can't match up with the saved identifier of path+UID. Using tooltip rather than simply relying on path gives us a better chance of not accidentally pinning the wrong icons from apps that use multiple icons.
=> Restore pinned notify icon by tooltip if UID inconsistent

src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTasks/TasksService.cs
Also now removes the prop from the Explorer taskbar if running (and restores after we dispose).
=> Refactor setting TaskbandHWND prop for ITaskbarList

src/ManagedShell.Common/Helpers/MouseHelper.cs, src/ManagedShell.Interop/NativeMethods.cs, src/ManagedShell.WindowsTray/NotificationArea.cs
Casting to unsigned caused havoc when mouse coords were negative (which happens with multiple monitors)
=> Fix notifyicon mouse coords with multiple monitors

src/ManagedShell.AppBar/FullScreenHelper.cs
Currently, FullScreenHelper will only remove a full-screen window from the full-screen windows list if it is no longer full-screen or if it has moved to another monitor. This means that a window obstructing it does not remove it from the full-screen list.
This changes the logic to instead only keep a window in the full-screen windows list in two scenarios:
- If it is foreground, full-screen, and hasn't moved to another monitor
- If it is still full-screen, no longer in the foreground, but the new foreground window is on another monitor
Effectively this means that full-screen windows will stay in the full-screen list unless they are obstructed, which is the desired behavior.
This should fix cairoshell/cairoshell#495 and dremin/RetroBar#171.
=> Improve full-screen logic

src/ManagedShell.AppBar/ManagedShell.AppBar.csproj, src/ManagedShell.Common/ManagedShell.Common.csproj, src/ManagedShell.Interop/ManagedShell.Interop.csproj, src/ManagedShell.ShellFolders/ManagedShell.ShellFolders.csproj, src/ManagedShell.UWPInterop/ManagedShell.UWPInterop.csproj, src/ManagedShell.WindowsTasks/ManagedShell.WindowsTasks.csproj, src/ManagedShell.WindowsTray/ManagedShell.WindowsTray.csproj, src/ManagedShell/ManagedShell.csproj
Fixes shell apps targeting .NET 6 being 25 MB larger than with other targets.
=> Use CsWinRT embedded instead of TFM to reduce size

src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs
If a window owns a popup and it was the most recently activated, bring it to the foreground. This matches Windows behavior tested back to Windows 2000.
Fixes dremin/RetroBar#353
=> Bring correct window to foreground

src/ManagedShell.ShellFolders/Enums/SLGP_FLAGS.cs, src/ManagedShell.ShellFolders/Enums/SLR_FLAGS.cs, src/ManagedShell.ShellFolders/Enums/STGM.cs, src/ManagedShell.ShellFolders/Interfaces/IShellLink.cs, src/ManagedShell.ShellFolders/ShellLink.cs, src/ManagedShell.ShellFolders/ShellLinkHelper.cs, src/ManagedShell.ShellFolders/Structs/WIN32_FIND_DATA.cs
Also adds the necessary interface definitions.
In the future we could create a nice link class that encapsulates link operations, but [IShellLink API](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ishelllinkw) is already fairly straightforward. The helper provides easy access to this, which I think should be good for now.
=> Adds ShellLinkHelper for some common link ops

src/ManagedShell.Common/Helpers/EnvironmentHelper.cs, src/ManagedShell.WindowsTray/NotificationArea.cs
The dark mode APIs we're using haven't changed, so we can probably count on them staying around.
=> Add more tray guids, remove dark mode build limit

src/ManagedShell.AppBar/AppBarScreen.cs, src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/Tasks.cs, src/ManagedShell.WindowsTasks/TasksService.cs, src/ManagedShell/ShellManager.cs
This is to be used with cairoshell/cairoshell#203.
The event for window LocationChange seems to fire constantly while a window moves. I tried MoveSizeEnd instead, but it is not exhaustive enough. I'm not seeing any performance issues with LocationChange however. If you're aware of a better way to track this, I'm all ears! I added a parameter to toggle this functionality in case the shell doesn't care.
=> Track hMonitor by window for multi-mon taskbars

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell/ShellConfig.cs, src/ManagedShell/ShellManager.cs
- ABM_ACTIVATE and ABM_WINDOWPOSCHANGED don't need to be forwarded to Explorer when we are running, so handle them. This fixes some cases of the Explorer taskbar raising when clicking tray icons, causing issues such as dremin/RetroBar#413.
- ShellConfig can now be used to enable or disable multi-mon tasks support.
=> ShellConfig option for multi-mon, handle more ABMs

src/ManagedShell.WindowsTasks/Tasks.cs
This way shells don't need to do all of the collection setup themselves when they want to make a custom task list filter, which is needed for multi-monitor-aware taskbars.
=> Add method to make multimon taskbars easier

src/ManagedShell.WindowsTasks/TasksService.cs, src/ManagedShell.WindowsTasks/WindowActivatedEventArgs.cs
There are several use cases for shells to receive an event when any window is activated, regardless of its taskbar visibility. This allows them to do so without polling.
TasksService.WindowActivated is fired whenever any window is activated (excluding the desktop/taskbar), and passes the window in args
TasksService.DesktopActivated is fired whenever the desktop/taskbar is activated only
In the future FullScreenHelper may be able to be refactored to use this instead of polling, when tasks are enabled.
=> Add events so shells can detect window activation without polling

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/AppBarMode.cs, src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.Interop/NativeMethods.Shell32.cs, src/ManagedShell.WindowsTasks/TasksService.cs
Cairo has a hacked together implementation of auto-hide. This PR adds support for auto-hide to AppBarWindow and AppBarManager so that any ManagedShell consumer can use auto-hide. It is also extensible so that, for example, shells can prevent auto-hide when attached panels etc are open.
I have ported Cairo to use the new auto-hide mechanism and have also used it to add auto-hide to RetroBar, so it seems to satisfy various use cases.
Also added an infinite-loop protection mechanism to AppBarManager from some unrelated debugging exercises that I thought would be good to keep.
=> Add auto-hide support for AppBars

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/AppBarWindow.cs
- Use SetWindowPos to resize in single operation
- Fix incorrect comparison logic in ABSetPos
- Add configurable auto-hide show delay
The big change here is coalescing the previous 4 separate size/pos updates (top, left, width, height) into 1 operation via SetWindowPos. This fixes a lot of the raciness I've seen with the positioning logic.
=> AppBar improvements

src/ManagedShell.Common/Helpers/ShellHelper.cs, src/ManagedShell.Common/Interfaces/IApplicationActivationManager.cs, src/ManagedShell.UWPInterop/StoreApp.cs, src/ManagedShell.UWPInterop/StoreAppHelper.cs
Shells can use ShellHelper.ActivateApplication to launch an app via AppUserModelID. This allows launches via AUMID without Explorer running.
=> Add app activation

src/ManagedShell.AppBar/AppBarWindow.cs
This means shells can use this function unguarded without causing animation code to run unnecessarily.
=> Don't run peek code if appbar not using autohide

src/ManagedShell.Common/Common/ThreadSafeObservableCollection.cs
I don't think a lock was actually being established with the existing code. This refactors the code to use a more modern, simple, and performant lock.
=> Hopefully fix ThreadSafeObservableCollection

src/ManagedShell.ShellFolders/ShellLinkHelper.cs
ShellLinkHelper.Load accepts an hwnd parameter to parent any UI shown by the link resolution process in case a broken shortcut is encountered. However, a shell may pass 0 in order to indicate no UI should be shown. This PR adds the necessary flag for that to actually happen.
=> Fix shell link resolution always showing UI

src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/NotificationBalloon.cs
Currently tray icons from apps that are using the [H.NotifyIcon library](https://github.com/HavenDV/H.NotifyIcon) are not working properly. The two issues are fixed in the PR:
1. Icon update messages are coming with a GUID instead of an HWnd. Previously we ignored these messages; now we handle them using the GUID.
2. Balloon messages were coming with a `0` value for the timeout (which makes sense, Explorer does not honor the timeout anyway). Now we use the system default timeout in this scenario.
An example application with this library is [DS4Windows](https://github.com/Ryochan7/DS4Windows/releases/), which was reported in dremin/RetroBar#730.
=> Fix tray icons for apps that use the H.NotifyIcon library

src/ManagedShell.AppBar/AppBarWindow.cs
Adds property change notification to AppBarWindow's DpiScale. This makes it easier for shells to update other properties based on DPI changes.
=> Make DpiScale observable

src/ManagedShell.Common/Helpers/EnvironmentHelper.cs, src/ManagedShell.WindowsTray/NotificationArea.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs
A few improvements:
1. In the original Windows 11 release, sending a mouse click to the network or power icons crashed ShellExperienceHost. In 22H2 it now shows a flyout as expected, so go back to just sending a mouse click if we're on 22H2.
2. Some legacy shell enablers such as StartAllBack break the action center keyboard shortcut, but restore the click-able sound icon. This means that only sending a keyboard shortcut doesn't work. On 22H2, since it is now safe to do so, send both the mouse click and the keyboard shortcut to cover all scenarios.
=> Improve tray icons in Windows 11 22H2+

src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.WindowsTray/NotifyIcon.cs
The ContextMenuOpening event is called even if no elements nor their parents have a contextmenu. This caused the appbar to think a menu was open when none was, getting it stuck. By recursively checking for a contextmenu, we can fix this.
Also made a notifyicon property public, because it is useful.
=> Fix auto-hide getting stuck when there is no context menu

src/ManagedShell.AppBar/AppBarManager.cs
I made a minor error here when I wrote #77. The `Actual` versions of these properties are more accurate, especially as part of DPI changes.
=> Fix incorrect "is same" logic, part 2

src/ManagedShell.Common/Helpers/IconHelper.cs, src/ManagedShell.Common/Helpers/ShellHelper.cs
It's possible, albeit uncommon, for the drive letter and/or Windows folder name to differ for users. For example, someone who upgraded from Windows 2000 may have the path D:\WINNT\system32.
=> Fix a couple hardcoded %WINDIR% paths

src/ManagedShell.Interop/NativeMethods.User32.cs
We will use these in Cairo for removable device notifications, allowing us to not impede device removal.
=> Add some useful pinvokes for device notifications

src/ManagedShell.ShellFolders/ShellFolder.cs
The shell may wish to temporarily disable the folder change watcher, as it blocks things such as device removal.
=> Allow shell to start or stop the folder change watcher after the folder is initialized

src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTray/TrayService.cs
This message is always posted when Explorer restarts, and when we forward it back via `SendMessage`, Explorer enters a crash loop on recent Windows 11. Forwarding it via `PostMessage` avoids crashing Explorer.
This should fix the following:
https://github.com/dremin/RetroBar/pull/945
https://github.com/dremin/RetroBar/issues/942
https://github.com/dremin/RetroBar/issues/938
https://github.com/dremin/RetroBar/issues/927
https://github.com/dremin/RetroBar/issues/648
https://github.com/dremin/RetroBar/issues/476
https://github.com/dremin/RetroBar/issues/457
=> Forward some Explorer messages via PostMessage

src/ManagedShell.ShellFolders/ChangeWatcher.cs, src/ManagedShell.ShellFolders/ShellFolder.cs
Currently the ShellFolders implementation does not properly handle hidden files:
- If a new hidden file is created, we don't check this and will still add the file to the collection, so it will be visible
- If a hidden file is renamed or modified, we will see that the file is not in the collection and add it, so it becomes visible
- If a visible file becomes hidden, the ChangeWatcher does not receive a notification of this and it remains visible
This PR fixes all of the above items.
=> Handle when the 'hidden' attribute changes

src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs
When switching virtual desktops, DWM marks all windows not on the current desktop as cloaked to hide them from the user and from the task switcher. We already had support for showing windows in the taskbar in response to the uncloak event; this PR adds support for hiding windows from the taskbar in response to the cloak event.
A good explanation regarding cloaked windows is [here](https://devblogs.microsoft.com/oldnewthing/20200302-00/?p=103507).
=> Handle cloak event to improve virtual desktop behavior

src/ManagedShell.Common/Helpers/ShellHelper.cs, src/ManagedShell.Interop/NativeMethods.Msi.cs, src/ManagedShell.ShellFolders/ShellLinkHelper.cs
Many shortcuts point to Microsoft Installer packages or have an associated PIDL we can read from, which provides a more accurate target than the string returned by `IShellLink.GetPath()`. Added a helper method so shells don't need to do this themselves.
Also added a missing `CloseHandle` to another helper.
=> Add helper method for getting shortcut target

src/ManagedShell.WindowsTasks/ApplicationWindow.cs
- Fix Start menu window showing in taskbar on early versions of Win10 (https://github.com/dremin/RetroBar/issues/765)
- Fix first selected window un-maximizing (https://github.com/dremin/RetroBar/issues/997)
=> Misc tasks fixes

src/ManagedShell.Common/Helpers/EnvironmentHelper.cs, src/ManagedShell.Interop/NativeMethods.ShlwApi.cs, src/ManagedShell.UWPInterop/ImmersiveShellHelper.cs, src/ManagedShell.UWPInterop/Interfaces/CImmersiveShell.cs, src/ManagedShell.UWPInterop/Interfaces/IActionCenterExperienceManager.cs, src/ManagedShell.UWPInterop/Interfaces/IControlCenterExperienceManager.cs, src/ManagedShell.UWPInterop/Interfaces/INetworkFlyoutExperienceManager.cs, src/ManagedShell.UWPInterop/Interfaces/INetworkFlyoutExperienceManager_19H2.cs, src/ManagedShell.UWPInterop/Interfaces/INetworkFlyoutExperienceManager_20H1.cs, src/ManagedShell.UWPInterop/Interfaces/IServiceProvider.cs, src/ManagedShell.UWPInterop/Interfaces/IShellExperienceManagerFactory.cs, src/ManagedShell.UWPInterop/Interfaces/ITrayBatteryFlyoutExperienceManager.cs, src/ManagedShell.UWPInterop/Interfaces/ITrayClockFlyoutExperienceManager.cs, src/ManagedShell.UWPInterop/Interfaces/ITrayMtcUvcFlyoutExperienceManager.cs, src/ManagedShell.UWPInterop/ManagedShell.UWPInterop.csproj, src/ManagedShell.UWPInterop/NativeMethods.cs, src/ManagedShell.UWPInterop/StoreAppHelper.cs
Enables shells to easily invoke:
- Battery flyout
- Clock flyout
- Network flyout
- Sound flyout
- Action center
- Control center
=> Add ImmersiveShellHelper

src/ManagedShell.WindowsTasks/ApplicationWindow.cs
When minimizing a window, it needs the ability to move focus the next window in the z-order. Previously this only worked when a debugger was attached to the shell, but this makes it work always. This fixes the problem described in https://github.com/dremin/RetroBar/issues/783.
=> Fix window focus after minimize when not debugging

src/ManagedShell.WindowsTasks/TasksService.cs
Remove some excessive logs and replace them with more useful ones that have window titles.
=> Improve TasksService logs with window title

src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.AppBar/FullScreenApp.cs, src/ManagedShell.AppBar/FullScreenHelper.cs, src/ManagedShell.AppBar/ManagedShell.AppBar.csproj, src/ManagedShell.Common/SupportingClasses/NativeWindowEx.cs, src/ManagedShell.Common/SupportingClasses/ShellWindow.cs, src/ManagedShell.Interop/NativeMethods.User32.cs, src/ManagedShell.Interop/NativeMethods.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs, src/ManagedShell.WindowsTasks/WindowEventArgs.cs, src/ManagedShell/ShellConfig.cs, src/ManagedShell/ShellManager.cs
Performance improvements:
- Use new shell hook messages in Win8+ for handling window monitor changes instead of event hook
- Use new shell hook messages in Win8+ for full-screen app notifications
- Adapt FullScreenHelper to use new TasksService events instead of a timer on Win8+
Fix handling of the minimize/restore animation:
- Fixed NativeWindowEx message object passing so that the result value is actually used
- Fix broken handling of HSHELL_GETMINRECT
- Added event to ApplicationWindow that shells can handle to provide a button rect when requested that is used for HSHELL_GETMINRECT
Misc:
- Added some properties to ApplicationWindow to simplify other code
- Improve FullScreenHelper logic and logging
- Fix ResetScreenCache on newer .NET versions …
=> Window management improvements and fixes

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/AppBarWindow.cs
- Get and use window coordinates in pixels instead of converting points to pixels when comparing AppBar rects
- Save latest AppBar rect in AppBarWindow, so that when multiple updates come quickly, the AppBar window does not bounce around any more due to the timer using stale data.
=> AppBar fixes

src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.Common/Helpers/WindowHelper.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/TasksService.cs
- Removed the ShowInTaskbar=false from AppBarWindow because all it does is creates a hidden owner window and removes the APPWINDOW style. We already have the TOOLWINDOW style so we don't need an owner to be hidden from the taskbar. Enhanced the helper that sets TOOLWINDOW to also remove APPWINDOW.
- Removed a lot of duplication across AppBarManager and AppBarWindow, mostly around sizing/positioning logic.
- Added a cache of the current window rect to AppBarWindow so that it doesn't have to be fetched as often.
- More consistently use pixels instead of performing math on WPF's points-based size/position values
- Removed the timer-based AppBar positioning hacks in favor of reacting to unexpected WM_WINDOWPOSCHANGED messages instead. Whenever we intentionally update our position, we set a …
=> AppBar refactoring and improvements

src/ManagedShell.WindowsTasks/ApplicationWindow.cs
On Windows 8 and newer, as of #123 we use the shell hook messages sent to us when a window moves to another monitor, instead of the global window move event hook that we use on Windows 7.
However, one limitation is that this tells us when the window moves to another monitor, but not necessarily when the monitor it is on is removed. When that happens, the cached HMonitor becomes incorrect.
When the system's displays change, shells that use this value are going to have to handle the display change events anyway to add/remove taskbars, so they will naturally fetch HMonitor from ApplicationWindow.
By ignoring the cached value in this scenario, we always end up with the correct value when it is needed. We still keep the cache around so that we can avoid triggering PropertyChanged events when …
=> Ignore monitor cache when using TasksService events

src/ManagedShell.AppBar/FullScreenApp.cs, src/ManagedShell.AppBar/FullScreenHelper.cs, src/ManagedShell.WindowsTasks/ApplicationWindow.cs, src/ManagedShell.WindowsTasks/FullScreenEventArgs.cs, src/ManagedShell.WindowsTasks/TasksService.cs
1. When TasksService receives a full-screen event, trust it more and skip screen bounds checks (but still do the other checks)
2. Maintain a list of inactive full-screen windows so that we don't lose state when a new foreground window is activated
3. Change bounds check to account for bordered popup windows
4. Add heuristic to prevent exiting full-screen when a topmost window is activated on top of a full-screen window, as Windows does
5. Related refactors
=> Improvements to full-screen logic

src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.AppBar/FullScreenApp.cs, src/ManagedShell.AppBar/FullScreenHelper.cs
Fixes a couple of things from #127:
1. Fix app leaving full screen not being removed from list while inactive
2. Always use bounds validation with auto-hide appbar to prevent maximized windows hiding the appbar
=> More full-screen fixes

src/ManagedShell.AppBar/AppBarEventArgs.cs, src/ManagedShell.AppBar/AppBarEventReason.cs, src/ManagedShell.AppBar/AppBarManager.cs, src/ManagedShell.AppBar/AppBarWindow.cs, src/ManagedShell.AppBar/ScreenSetupReason.cs
Removes Cairo-specific functionality and enum values that shouldn't be in ManagedShell. They will be re-added as part of Cairo instead.
=> Remove Cairo-specific code

src/ManagedShell.WindowsTasks/ApplicationWindow.cs
Set the window as foreground before closing so that any prompts for saving data, etc, are not hidden behind other windows. Matches explorer behavior.
=> Fix closing task not correctly coming to foreground

src/ManagedShell.WindowsTasks/ApplicationWindow.cs
Fixes #132. The system sets the `ITaskList_Deleted` window prop when an application [uses](https://github.com/tauri-apps/tao/blob/dae6d8875dbc10ce0ab45d9a00072436b3688b0e/src/platform_impl/windows/window.rs#L1512) `ITaskbarList::DeleteTab`.
=> Don't add deleted tasks

src/ManagedShell.Interop/NativeMethods.User32.cs
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey
=> Add MOD enum for keyboard modifier keys
